//! Build-time generator for the frontend's static metadata.
//!
//! Everything emitted here is derived from [`portfolio_data::CONFIG`] so the
//! single source of truth for site facts (name, URL, social links, …) lives in
//! one place instead of being hand-duplicated across `index.html`, `robots.txt`,
//! `sitemap.xml` and the web manifest.
//!
//! Run by Trunk as a `pre_build` hook (see `apps/frontend/Trunk.toml`). The
//! output directory is taken from `TRUNK_SOURCE_DIR` (set by Trunk to the
//! directory containing `index.html`), or the first CLI argument, defaulting to
//! the current directory. Files land in `<out>/generated/` and are picked up by
//! the `data-trunk` links in `index.html`.

use std::env;
use std::fs;
use std::path::PathBuf;

use portfolio_data::{CONFIG, LANGUAGES};
use serde_json::json;

fn main() -> std::io::Result<()> {
    let base = env::var_os("TRUNK_SOURCE_DIR")
        .map(PathBuf::from)
        .or_else(|| env::args_os().nth(1).map(PathBuf::from))
        .unwrap_or_else(|| PathBuf::from("."));
    let out = base.join("generated");
    fs::create_dir_all(&out)?;
    // Ensure the served resume directory exists so the `copy-dir` link in
    // index.html resolves even in dev builds where no resumes were generated.
    fs::create_dir_all(out.join("resume"))?;

    fs::write(out.join("head.html"), head_html())?;
    fs::write(out.join("robots.txt"), robots_txt())?;
    fs::write(out.join("sitemap.xml"), sitemap_xml())?;
    fs::write(out.join("site.webmanifest"), webmanifest())?;

    println!(
        "site-meta: wrote head.html, robots.txt, sitemap.xml, site.webmanifest to {}",
        out.display()
    );
    Ok(())
}

/// The `<head>` SEO/social block, inlined into `index.html` via `rel="inline"`.
fn head_html() -> String {
    let c = &CONFIG;
    let canonical = format!("{}/", c.url);
    let keywords = c.keywords.join(", ");

    // og:locale is the default language; every other language is an alternate.
    let alternates: String = LANGUAGES
        .iter()
        .skip(1)
        .map(|l| {
            format!(
                "<meta property=\"og:locale:alternate\" content=\"{}\" />\n",
                attr(l)
            )
        })
        .collect();

    let json_ld = serde_json::to_string_pretty(&json!([
        {
            "@context": "https://schema.org",
            "@type": "Person",
            "name": c.full_name,
            "email": c.email,
            "jobTitle": c.job_title,
            "url": c.url,
            "sameAs": [c.github, c.linkedin],
        },
        {
            "@context": "https://schema.org",
            "@type": "WebSite",
            "name": c.title,
            "description": c.description,
            "url": c.url,
        },
    ]))
    .expect("JSON-LD serializes");

    let title = c.title;
    let mut head = String::new();
    head.push_str("<!-- Generated by `site-meta` from portfolio-data::CONFIG. Do not edit. -->\n");
    head.push_str(&format!("<title>{}</title>\n", text(title)));
    head.push_str(&meta_name("description", c.description));
    head.push_str(&meta_name("keywords", &keywords));
    head.push_str(&meta_name("author", c.full_name));
    head.push_str(&format!(
        "<link rel=\"canonical\" href=\"{}\" />\n\n",
        attr(&canonical)
    ));

    head.push_str(&meta_prop("og:type", "website"));
    head.push_str(&meta_prop("og:url", &canonical));
    head.push_str(&meta_prop("og:title", title));
    head.push_str(&meta_prop("og:description", c.description));
    head.push_str(&meta_prop("og:site_name", title));
    head.push_str(&meta_prop("og:locale", LANGUAGES[0]));
    head.push_str(&alternates);
    head.push_str(&meta_name("twitter:card", "summary"));
    head.push_str(&meta_name("twitter:title", title));
    head.push_str(&meta_name("twitter:description", c.description));

    head.push_str(&format!(
        "\n<script type=\"application/ld+json\">\n{json_ld}\n</script>\n"
    ));
    head
}

fn robots_txt() -> String {
    format!(
        "User-Agent: *\nAllow: /\nDisallow: /api/\n\nSitemap: {}/sitemap.xml\n",
        CONFIG.url
    )
}

fn sitemap_xml() -> String {
    // Paths mirror the routes in `apps/frontend/src/router.rs`.
    let entry = |path: &str, changefreq: &str, priority: &str| {
        format!(
            "  <url>\n    <loc>{}{path}</loc>\n    <changefreq>{changefreq}</changefreq>\n    <priority>{priority}</priority>\n  </url>\n",
            CONFIG.url
        )
    };
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n\
         {}{}{}</urlset>\n",
        entry("/", "weekly", "1.0"),
        entry("/imprint", "monthly", "0.5"),
        entry("/privacy", "monthly", "0.5"),
    )
}

fn webmanifest() -> String {
    let c = &CONFIG;
    let manifest = json!({
        "name": c.title,
        "short_name": c.full_name,
        "description": c.description,
        "id": "portfolio",
        "start_url": "/",
        "display": "standalone",
        "background_color": "#0a0d14",
        "theme_color": "#0a0d14",
        "categories": ["productivity", "portfolio", "developer"],
        "icons": [{
            "src": "/favicon.svg",
            "sizes": "any",
            "type": "image/svg+xml",
            "purpose": "any",
        }],
    });
    serde_json::to_string_pretty(&manifest).expect("manifest serializes") + "\n"
}

fn meta_name(name: &str, content: &str) -> String {
    format!(
        "<meta name=\"{}\" content=\"{}\" />\n",
        attr(name),
        attr(content)
    )
}

fn meta_prop(property: &str, content: &str) -> String {
    format!(
        "<meta property=\"{}\" content=\"{}\" />\n",
        attr(property),
        attr(content)
    )
}

/// Escapes a string for use inside a double-quoted HTML attribute.
fn attr(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

/// Escapes a string for use as HTML text content.
fn text(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn attr_escapes_all_dangerous_characters() {
        assert_eq!(
            attr(r#"a & b < c > d " e"#),
            "a &amp; b &lt; c &gt; d &quot; e"
        );
    }

    #[test]
    fn text_escapes_markup_but_keeps_quotes() {
        // Text content does not need quote escaping, unlike attributes.
        assert_eq!(text(r#"<a> & "b""#), r#"&lt;a&gt; &amp; "b""#);
    }

    #[test]
    fn robots_allows_crawling_but_blocks_the_api_and_links_the_sitemap() {
        let robots = robots_txt();
        assert!(robots.contains("User-Agent: *"));
        assert!(robots.contains("Allow: /"));
        assert!(robots.contains("Disallow: /api/"));
        assert!(robots.contains(&format!("Sitemap: {}/sitemap.xml", CONFIG.url)));
    }

    #[test]
    fn sitemap_lists_every_public_route() {
        let xml = sitemap_xml();
        assert!(xml.starts_with("<?xml"));
        for path in ["/", "/imprint", "/privacy"] {
            assert!(
                xml.contains(&format!("<loc>{}{path}</loc>", CONFIG.url)),
                "sitemap missing route {path}"
            );
        }
        assert_eq!(xml.matches("<url>").count(), 3);
    }

    #[test]
    fn webmanifest_is_valid_json_derived_from_config() {
        let manifest: serde_json::Value =
            serde_json::from_str(&webmanifest()).expect("manifest is valid JSON");
        assert_eq!(manifest["name"], CONFIG.title);
        assert_eq!(manifest["short_name"], CONFIG.full_name);
        assert_eq!(manifest["start_url"], "/");
        assert!(manifest["icons"].as_array().is_some_and(|i| !i.is_empty()));
    }

    #[test]
    fn head_carries_canonical_title_and_structured_data() {
        let head = head_html();
        assert!(head.contains(&format!("<title>{}</title>", text(CONFIG.title))));
        assert!(head.contains(&format!("<link rel=\"canonical\" href=\"{}/\"", CONFIG.url)));
        assert!(head.contains("application/ld+json"));
        // The default language is the og:locale; alternates cover the rest.
        assert!(head.contains(&format!("content=\"{}\"", LANGUAGES[0])));
        for lang in LANGUAGES.iter().skip(1) {
            assert!(
                head.contains(&format!(
                    "og:locale:alternate\" content=\"{lang}\""
                )),
                "missing alternate locale {lang}"
            );
        }
    }

    #[test]
    fn head_json_ld_is_well_formed() {
        let head = head_html();
        let open = head.find("<script type=\"application/ld+json\">").unwrap();
        let start = head[open..].find('\n').unwrap() + open + 1;
        let end = head[start..].find("</script>").unwrap() + start;
        let json: serde_json::Value =
            serde_json::from_str(head[start..end].trim()).expect("JSON-LD parses");
        let entities = json.as_array().expect("JSON-LD is an array");
        assert_eq!(entities.len(), 2);
        assert_eq!(entities[0]["name"], CONFIG.full_name);
        assert_eq!(entities[0]["email"], CONFIG.email);
    }
}
