name: 'Update Helm Chart'
description: 'Updates the helm chart with a new version and image digest, and creates a PR.'
inputs:
  app-id:
    description: 'GitHub App ID'
    required: true
  private-key:
    description: 'GitHub App Private Key'
    required: true
  helm-repo:
    description: 'Repository name of the helm charts (e.g. owner/repo)'
    default: 'TimSchoenle/helm-charts'
    required: false
  chart-path:
    description: 'Path of the chart inside the repo'
    default: 'charts/portfolio'
    required: false
  checkout-path:
    description: 'Path to checkout the helm repo to'
    default: 'helm-charts'
    required: false
  new-tag:
    description: 'New release tag'
    required: true
  image-digest:
    description: 'Docker image digest'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Parse Repo
      id: parse_repo
      shell: bash
      run: |
        FULL_REPO="${{ inputs.helm-repo }}"
        OWNER="${FULL_REPO%%/*}"
        REPO="${FULL_REPO#*/}"
        echo "owner=$OWNER" >> "$GITHUB_OUTPUT"
        echo "repo=$REPO" >> "$GITHUB_OUTPUT"

    - name: Generate Bot Token
      id: generate_token
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ steps.parse_repo.outputs.owner }}
        repositories: ${{ steps.parse_repo.outputs.repo }}

    - name: Checkout Helm Charts
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        repository: ${{ inputs.helm-repo }}
        token: ${{ steps.generate_token.outputs.token }}
        path: ${{ inputs.checkout-path }}
        fetch-depth: 0

    - name: Get GitHub App User ID
      id: get-user-id
      shell: bash
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: echo "user-id=$(gh api "/users/${{ steps.generate_token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"

    - name: Install yq
      uses: dcarbone/install-yq-action@4075b4dca348d74bd83f2bf82d30f25d7c54539b # v1.3.1
      with:
        version: 'v4.44.1'

    - name: Update Chart Version
      shell: bash
      working-directory: ${{ inputs.checkout-path }}/${{ inputs.chart-path }}
      env:
        NEW_TAG: ${{ inputs.new-tag }}
        IMAGE_DIGEST: ${{ inputs.image-digest }}
      run: |
        # Bump patch version
        # Extract current version
        CURRENT_VERSION=$(yq '.version' Chart.yaml)
        echo "Current Version: $CURRENT_VERSION"

        # Increment patch
        NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
        echo "New Version: $NEW_VERSION"

        # Update Chart.yaml
        yq -i ".version = \"$NEW_VERSION\"" Chart.yaml
        yq -i ".appVersion = \"$NEW_TAG\"" Chart.yaml

        # Update values.yaml image tag
        # Use yq to find the line number of .image.tag to preserve formatting/comments/empty lines
        # https://github.com/mikefarah/yq/issues/515
        TAG_LINE=$(yq '.image.tag | line' values.yaml)
        echo "Line number for image.tag: $TAG_LINE"

        # Use sed to replace the line in place
        # Format: [TAG]@[DIGEST]
        FULL_TAG="${NEW_TAG}@${IMAGE_DIGEST}"
        echo "New Image Tag: $FULL_TAG"

        # sed is 1-indexed, yq line is 1-indexed
        # Using sed to replace the content of that specific line
        sed -i "${TAG_LINE}s|tag: .*|tag: $FULL_TAG|" values.yaml

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ steps.generate_token.outputs.token }}
        path: ${{ inputs.checkout-path }}
        branch: chore/portfolio/automatic/${{ inputs.new-tag }}
        title: 'chore(portfolio): update chart for release ${{ inputs.new-tag }}'
        body: 'Automated update for Portfolio release [${{ inputs.new-tag }}](https://github.com/${{ github.repository }}/releases/tag/${{ inputs.new-tag }}).'
        commit-message: 'chore(portfolio): update chart for release ${{ inputs.new-tag }}'
        committer: '${{ steps.generate_token.outputs.app-slug }}[bot] <${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate_token.outputs.app-slug }}[bot]@users.noreply.github.com>'
        author: '${{ steps.generate_token.outputs.app-slug }}[bot] <${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate_token.outputs.app-slug }}[bot]@users.noreply.github.com>'
        delete-branch: true
